package com.retropoktan.alinone.alinoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALINONE_ORDER.
 */
public class AlinoneOrder {

    private Long id;
    /** Not-null value. */
    private String orderID;
    /** Not-null value. */
    private String objectPhone;
    /** Not-null value. */
    private String orderAddress;
    /** Not-null value. */
    private String merchantID;
    /** Not-null value. */
    private java.util.Date orderTime;

    public AlinoneOrder() {
    }

    public AlinoneOrder(Long id) {
        this.id = id;
    }

    public AlinoneOrder(Long id, String orderID, String objectPhone, String orderAddress, String merchantID, java.util.Date orderTime) {
        this.id = id;
        this.orderID = orderID;
        this.objectPhone = objectPhone;
        this.orderAddress = orderAddress;
        this.merchantID = merchantID;
        this.orderTime = orderTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderID() {
        return orderID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderID(String orderID) {
        this.orderID = orderID;
    }

    /** Not-null value. */
    public String getObjectPhone() {
        return objectPhone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectPhone(String objectPhone) {
        this.objectPhone = objectPhone;
    }

    /** Not-null value. */
    public String getOrderAddress() {
        return orderAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }

    /** Not-null value. */
    public String getMerchantID() {
        return merchantID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMerchantID(String merchantID) {
        this.merchantID = merchantID;
    }

    /** Not-null value. */
    public java.util.Date getOrderTime() {
        return orderTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderTime(java.util.Date orderTime) {
        this.orderTime = orderTime;
    }

}
