package com.retropoktan.alinone.alinoneDao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alinoneOrderDaoConfig;
    private final DaoConfig merchantDaoConfig;

    private final AlinoneOrderDao alinoneOrderDao;
    private final MerchantDao merchantDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alinoneOrderDaoConfig = daoConfigMap.get(AlinoneOrderDao.class).clone();
        alinoneOrderDaoConfig.initIdentityScope(type);

        merchantDaoConfig = daoConfigMap.get(MerchantDao.class).clone();
        merchantDaoConfig.initIdentityScope(type);

        alinoneOrderDao = new AlinoneOrderDao(alinoneOrderDaoConfig, this);
        merchantDao = new MerchantDao(merchantDaoConfig, this);

        registerDao(AlinoneOrder.class, alinoneOrderDao);
        registerDao(Merchant.class, merchantDao);
    }
    
    public void clear() {
        alinoneOrderDaoConfig.getIdentityScope().clear();
        merchantDaoConfig.getIdentityScope().clear();
    }

    public AlinoneOrderDao getAlinoneOrderDao() {
        return alinoneOrderDao;
    }

    public MerchantDao getMerchantDao() {
        return merchantDao;
    }

}
