package com.retropoktan.alinone.alinoneDao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig merchantDaoConfig;

    private final OrderDao orderDao;
    private final MerchantDao merchantDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        merchantDaoConfig = daoConfigMap.get(MerchantDao.class).clone();
        merchantDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        merchantDao = new MerchantDao(merchantDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(Merchant.class, merchantDao);
    }
    
    public void clear() {
        orderDaoConfig.getIdentityScope().clear();
        merchantDaoConfig.getIdentityScope().clear();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public MerchantDao getMerchantDao() {
        return merchantDao;
    }

}
